### PR TITLE
JunOS time

### PR DESCRIPTION
**Pull request by bonishvarik**
Hi! I just added simple junos driver and some tests to your project.

### CODE REVIEW

**Comment by ogenstad** [comment]
Thanks!

I'd like to be able to have a way to test all of the platforms within the project for future changes/integration tests. As I'm not a Junos user/customer do you have any recommendations in terms of what I'd be able to use. I know they had some Vagrant images a few years ago, perhaps they have public Docker images now?

**Comment by bonishvarik** [comment]
I tested on EVE-NG only. But I think this will help you: https://github.com/Juniper/OpenJNPR-Container-vMX
I will try to check it few days.

**Comment by ogenstad** [comment]
I've done some tests with this and there seems to be something of a timing issue for the first commands. When connecting to a device and running a single command then capturing the output it seems like the first command would instead capture the output from `"set cli screen-length 0` I.e. "Screen length set to 0", did you notice anything like that? I'm not sure if it's really something with the PR or if something else is needed in the package, but I haven't seen this behaviour with the other drivers.

One other thing I'd previously forgotten to add the linting checks to the CI. Would you mind looking at those there were some minor issues?

**Comment by bonishvarik** [comment]
So strange behavior. I'll check it and give feedback

**Comment by bonishvarik** [comment]
Which version Junos did you use when you got the issue with  "Screen length set to 0"? 
I checked 19.4 - no problem.

**Comment by bonishvarik** [comment]
The problem is on 14.1 and 15.1 versions

**Comment by ogenstad** [comment]
Do you see it constantly with 14.1 and 15.1 or just occasionally?

I was running against 20.4R1.12 against a Docker container. I've just merged #20 which allows requires a change for this PR. The establishConnection helper now requires a slice of strings as the last argument, i.e. the code here: `establishConnection(ctx, j, j.Connection, j.basePrompt(), "set cli screen-length 0")`

It's for platforms that might require several commands to prepare the terminal settings. I wonder if the same behaviour would be seen if you add a second empty command when using the latest commit in the branch. It would basically just sent an enter command without doing anything. Could you mind rebasing from the main branch and pushing up an update?

I'm also going to do some changes to the return values from Configure as described in #18, but it would perhaps be nice if we could get this one in first.

**Comment by bonishvarik** [comment]
Sure, I will do changes and add empty command. Just wanted to try an empty command

**Comment by ogenstad** [comment]
FYI, I just merged a change to the Configure signature as mentioned previously. So once you update this PR you'll have to take that into account

**Comment by bonishvarik** [comment]
Hello. Okay. I tested some variables yesterday to solve the problem, but still doesn't work. I will think about it yet

**Comment by ogenstad** [comment]
Ok, no worries perhaps you can push the latest changes and I'll also have a look to see if I figure something out.

**Pull request closed without merging**
