### PR TITLE
another approach to blocking reader

### PR DESCRIPTION
**Pull request by hellt**
@ogenstad this is an implementation of another the approach discussed in #11 

I wonder if you want to test this one side-to-side with #11 with injecting `runtime.NumGoroutine()` to check the differences.

### CODE REVIEW

**Comment by hellt** [comment]
Also I noticed that the `ctx` that you pass to `device.Dial()` does not have any effect on ssh dial timeout, since `ssh.Dial()` doesn't take in contexts

In 5a4f8cb I added a new netrasp option that is used to set up the dialing timout

**Comment by ogenstad** [comment]
Yeah, I've thought of that too just hadn't created an issue for it. I found this comment a while back and was going to do something like this: https://github.com/golang/go/issues/20288#issuecomment-707078634

But it's probably a good idea to allow users to set the timeout regardless.

**Comment by hellt** [comment]
In pursuit for understand this use case better I added a few print statements to track which goroutine do what:


```go
func (c *contextReader) Read(p []byte) (n int, err error) {
	ctx, cancel := context.WithCancel(c.ctx)
	defer cancel()
	rrCh := make(chan *readResult)

	go func() {
		id := rand.Intn(300)
		dead, _ := ctx.Deadline()
		fmt.Printf("goroutine %v started, context expires in %v\n", id, dead.Sub(time.Now()))
		select {
		case rrCh <- c.read(p, id):
			fmt.Printf("goroutine %v ended on received result from ssh channel\n", id)
		case <-ctx.Done():
			fmt.Printf("goroutine %v ended on ctx timeout\n", id)
		}
	}()

	select {
	case <-ctx.Done():
		return 0, ctx.Err()
	case rr := <-rrCh:
		return rr.n, rr.err
	}
}

func (c *contextReader) read(p []byte, id int) *readResult {
	fmt.Printf("read %v is called\n", id)
	n, err := c.r.Read(p)
	fmt.Printf("read %v returned result\n", id)
	return &readResult{n, err}
}
``` 

And this produced interesting results, I wonder how would you read it @ogenstad @karimra

```
❯ go run main.go
Number of go routines 1
goroutine 281 started, context expires in 4.90112636s
read 281 is called
goroutine 87 started, context expires in 4.90106682s
read 87 is called
read 87 returned result
goroutine 87 ended on received result from ssh channel
read 281 returned result
goroutine 281 ended on received result from ssh channel
goroutine 47 started, context expires in 4.860420606s
read 47 is called
goroutine 59 started, context expires in 4.860390995s
read 59 is called
read 59 returned result
goroutine 59 ended on received result from ssh channel
read 47 returned result
goroutine 47 ended on received result from ssh channel
goroutine 181 started, context expires in 4.850454949s
read 181 is called
goroutine 18 started, context expires in 4.850400268s
read 18 is called
read 18 returned result
goroutine 18 ended on received result from ssh channel
read 181 returned result
goroutine 181 ended on received result from ssh channel
goroutine 25 started, context expires in 4.84977369s
read 25 is called
goroutine 140 started, context expires in 4.849742155s
read 140 is called
read 140 returned result
goroutine 140 ended on received result from ssh channel
read 25 returned result
goroutine 25 ended on received result from ssh channel
goroutine 256 started, context expires in 4.846983652s
read 256 is called
goroutine 0 started, context expires in 4.846932838s
read 0 is called
read 0 returned result
goroutine 0 ended on received result from ssh channel
read 256 returned result
goroutine 256 ended on received result from ssh channel
goroutine 194 started, context expires in 4.845893036s
read 194 is called
goroutine 211 started, context expires in 4.845871747s
read 211 is called
read 211 returned result
goroutine 211 ended on received result from ssh channel
read 194 returned result
goroutine 194 ended on received result from ssh channel
goroutine 162 started, context expires in 4.845005552s
read 162 is called
goroutine 89 started, context expires in 4.844991921s
read 89 is called
read 89 returned result
goroutine 89 ended on received result from ssh channel
read 162 returned result
goroutine 162 ended on received result from ssh channel
goroutine 28 started, context expires in 4.843043309s
read 28 is called
goroutine 74 started, context expires in 4.843024587s
read 74 is called
read 74 returned result
goroutine 74 ended on received result from ssh channel
read 28 returned result
goroutine 28 ended on received result from ssh channel
goroutine 111 started, context expires in 4.841613469s
read 111 is called
goroutine 245 started, context expires in 4.841562944s
read 245 is called
read 245 returned result
goroutine 245 ended on received result from ssh channel
read 111 returned result
goroutine 111 ended on received result from ssh channel
goroutine 137 started, context expires in 4.839448105s
read 137 is called
goroutine 206 started, context expires in 4.83942552s
read 206 is called
read 206 returned result
goroutine 206 ended on received result from ssh channel
read 137 returned result
goroutine 137 ended on received result from ssh channel
goroutine 95 started, context expires in 4.838072011s
read 95 is called
goroutine 66 started, context expires in 4.838040842s
read 66 is called
read 66 returned result
goroutine 66 ended on received result from ssh channel
read 95 returned result
goroutine 95 ended on received result from ssh channel
goroutine 128 started, context expires in 4.837677785s
read 128 is called
goroutine 58 started, context expires in 4.837644321s
read 58 is called
read 58 returned result
goroutine 58 ended on received result from ssh channel
read 128 returned result
goroutine 128 ended on received result from ssh channel
goroutine 147 started, context expires in 4.833760077s
read 147 is called
goroutine 247 started, context expires in 4.833740053s
read 247 is called
read 247 returned result
goroutine 247 ended on received result from ssh channel
read 147 returned result
goroutine 147 ended on received result from ssh channel
goroutine 187 started, context expires in 4.830589747s
read 187 is called
goroutine 88 started, context expires in 4.83056296s
read 88 is called
read 88 returned result
goroutine 88 ended on received result from ssh channel
read 187 returned result
goroutine 187 ended on received result from ssh channel
goroutine 90 started, context expires in 4.829022199s
read 90 is called
goroutine 15 started, context expires in 4.828968776s
read 15 is called
read 15 returned result
goroutine 15 ended on received result from ssh channel
read 90 returned result
goroutine 90 ended on received result from ssh channel
goroutine 241 started, context expires in 4.826555065s
read 241 is called
goroutine 108 started, context expires in 4.82651065s
read 108 is called
read 108 returned result
goroutine 108 ended on received result from ssh channel
read 241 returned result
goroutine 241 ended on received result from ssh channel
goroutine 287 started, context expires in 4.825557662s
read 287 is called
goroutine 131 started, context expires in 4.825530161s
read 131 is called
read 131 returned result
goroutine 131 ended on received result from ssh channel
read 287 returned result
goroutine 287 ended on received result from ssh channel
goroutine 129 started, context expires in 4.824447165s
read 129 is called
goroutine 56 started, context expires in 4.824420789s
read 56 is called
read 56 returned result
goroutine 56 ended on received result from ssh channel
read 129 returned result
goroutine 129 ended on received result from ssh channel
goroutine 237 started, context expires in 4.819375864s
read 237 is called
goroutine 31 started, context expires in 4.819334376s
read 31 is called
read 31 returned result
goroutine 31 ended on received result from ssh channel
read 237 returned result
goroutine 237 ended on received result from ssh channel
goroutine 285 started, context expires in 4.817319975s
read 285 is called
goroutine 126 started, context expires in 4.817284708s
read 126 is called
read 126 returned result
goroutine 126 ended on received result from ssh channel
read 285 returned result
goroutine 285 ended on received result from ssh channel
################################################
### Connected
################################################
Sending command: show arp
Comment:  hello
Number of go routines 9
Output:
goroutine 13 started, context expires in 2.999888565s
read 13 is called
goroutine 190 started, context expires in 2.999835848s
read 190 is called
read 190 returned result
goroutine 190 ended on received result from ssh channel
read 13 returned result
goroutine 13 ended on received result from ssh channel
goroutine 94 started, context expires in 2.915901753s
read 94 is called
goroutine 63 started, context expires in 2.915777347s
read 63 is called
read 63 returned result
goroutine 63 ended on received result from ssh channel
read 94 returned result
goroutine 94 ended on received result from ssh channel
goroutine 133 started, context expires in 2.915532148s
read 133 is called
goroutine 147 started, context expires in 2.915511174s
read 147 is called
read 147 returned result
goroutine 147 ended on received result from ssh channel
read 133 returned result
goroutine 133 ended on received result from ssh channel
goroutine 178 started, context expires in 2.912428404s
read 178 is called
goroutine 124 started, context expires in 2.912372772s
read 124 is called
read 124 returned result
goroutine 124 ended on received result from ssh channel
read 178 returned result
goroutine 178 ended on received result from ssh channel
goroutine 259 started, context expires in 2.910965542s
read 259 is called
goroutine 153 started, context expires in 2.910946114s
read 153 is called
read 153 returned result
goroutine 153 ended on received result from ssh channel
read 259 returned result
goroutine 259 ended on received result from ssh channel
goroutine 57 started, context expires in 2.910180936s
read 57 is called
goroutine 121 started, context expires in 2.91016246s
read 121 is called
read 121 returned result
goroutine 121 ended on received result from ssh channel
read 57 returned result
goroutine 57 ended on received result from ssh channel
goroutine 189 started, context expires in 2.908178935s
read 189 is called
goroutine 99 started, context expires in 2.908158102s
read 99 is called
read 99 returned result
goroutine 99 ended on received result from ssh channel
read 189 returned result
goroutine 189 ended on received result from ssh channel
goroutine 100 started, context expires in 2.906826315s
read 100 is called
goroutine 205 started, context expires in 2.906779911s
read 205 is called
read 205 returned result
goroutine 205 ended on received result from ssh channel
read 100 returned result
goroutine 100 ended on received result from ssh channel
goroutine 188 started, context expires in 2.906475642s
read 188 is called
goroutine 138 started, context expires in 2.906454619s
read 138 is called
read 138 returned result
goroutine 138 ended on received result from ssh channel
read 188 returned result
goroutine 188 ended on received result from ssh channel
goroutine 103 started, context expires in 2.904135708s
read 103 is called
goroutine 155 started, context expires in 2.904081919s
read 155 is called
read 155 returned result
goroutine 155 ended on received result from ssh channel
read 103 returned result
goroutine 103 ended on received result from ssh channel
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  10.0.0.2              167   5255.0a00.0002  ARPA   GigabitEthernet1
Internet  10.0.0.15               -   5254.0023.4700  ARPA   GigabitEthernet1

Number of go routines 9
################################################
Sending command: ping
Comment:  Starting ping for the first blocking command
Number of go routines 9
Output:
goroutine 251 started, context expires in 2.999941035s
read 251 is called
goroutine 210 started, context expires in 2.999909833s
read 210 is called
read 210 returned result
goroutine 210 ended on received result from ssh channel
read 251 returned result
goroutine 251 ended on received result from ssh channel
goroutine 105 started, context expires in 2.974634878s
read 105 is called
goroutine 156 started, context expires in 2.974601483s
read 156 is called
read 156 returned result
goroutine 156 ended on received result from ssh channel
read 105 returned result
goroutine 105 ended on received result from ssh channel
goroutine 166 started, context expires in 2.97432273s
read 166 is called
goroutine 128 started, context expires in 2.974262897s
read 128 is called
read 128 returned result
goroutine 128 ended on received result from ssh channel
read 166 returned result
goroutine 166 ended on received result from ssh channel
goroutine 161 started, context expires in 2.972261274s
read 161 is called
goroutine 2 started, context expires in 2.97224511s
read 2 is called
read 2 returned result
goroutine 2 ended on received result from ssh channel
read 161 returned result
goroutine 161 ended on received result from ssh channel
goroutine 83 started, context expires in 2.969358146s
read 83 is called
goroutine 146 started, context expires in 2.969334017s
read 146 is called
read 146 returned result
goroutine 146 ended on received result from ssh channel
read 83 returned result
goroutine 83 ended on received result from ssh channel
goroutine 163 started, context expires in 2.968877329s
read 163 is called
goroutine 276 started, context expires in 2.968859734s
read 276 is called
read 276 returned result
goroutine 276 ended on received result from ssh channel
read 163 returned result
goroutine 163 ended on received result from ssh channel
goroutine 2 started, context expires in 2.953256809s
read 2 is called
goroutine 218 started, context expires in 2.953201021s
read 218 is called
read 2 returned result
goroutine 2 ended on ctx timeout
unable to run command: error reading output from device reader error: context deadline exceeded

Number of go routines 10
################################################
Sending command: 
Comment:  First enter
Number of go routines 10
Output:
goroutine 147 started, context expires in 2.999854586s
read 147 is called
goroutine 294 started, context expires in 2.999804606s
read 294 is called
read 218 returned result
goroutine 218 ended on ctx timeout
read 147 returned result
goroutine 147 ended on ctx timeout
unable to run command: error reading output from device reader error: context deadline exceeded

Number of go routines 10
################################################
Sending command: 10.0.0.15
Comment:  Ping target
Number of go routines 10
Output:
goroutine 277 started, context expires in 2.999825812s
read 277 is called
goroutine 163 started, context expires in 2.999792074s
read 163 is called
read 294 returned result
goroutine 294 ended on ctx timeout
read 163 returned result
goroutine 163 ended on received result from ssh channel
read 277 returned result
goroutine 277 ended on received result from ssh channel
goroutine 196 started, context expires in 2.988924168s
read 196 is called
goroutine 20 started, context expires in 2.988888814s
read 20 is called
read 20 returned result
goroutine 20 ended on received result from ssh channel
read 196 returned result
goroutine 196 ended on received result from ssh channel
goroutine 123 started, context expires in 2.987283508s
read 123 is called
goroutine 153 started, context expires in 2.987215824s
read 153 is called
read 153 returned result
goroutine 153 ended on received result from ssh channel
read 123 returned result
goroutine 123 ended on received result from ssh channel
goroutine 37 started, context expires in 2.985541389s
read 37 is called
goroutine 133 started, context expires in 2.985520568s
read 133 is called
read 133 returned result
goroutine 133 ended on received result from ssh channel
read 37 returned result
goroutine 37 ended on received result from ssh channel
goroutine 41 started, context expires in 2.984512854s
read 41 is called
goroutine 259 started, context expires in 2.984476066s
read 259 is called
read 259 returned result
goroutine 259 ended on received result from ssh channel
read 41 returned result
goroutine 41 ended on received result from ssh channel
goroutine 233 started, context expires in 2.982470437s
read 233 is called
goroutine 143 started, context expires in 2.982448038s
read 143 is called
read 143 returned result
goroutine 143 ended on received result from ssh channel
read 233 returned result
goroutine 233 ended on received result from ssh channel
goroutine 191 started, context expires in 2.981253914s
read 191 is called
goroutine 202 started, context expires in 2.981203906s
read 202 is called
read 202 returned result
goroutine 202 ended on received result from ssh channel
read 191 returned result
goroutine 191 ended on received result from ssh channel
goroutine 278 started, context expires in 2.979498386s
read 278 is called
goroutine 136 started, context expires in 2.979465069s
read 136 is called
read 136 returned result
goroutine 136 ended on received result from ssh channel
read 278 returned result
goroutine 278 ended on received result from ssh channel
goroutine 246 started, context expires in 2.978192411s
read 246 is called
goroutine 7 started, context expires in 2.978159326s
read 7 is called
read 7 returned result
goroutine 7 ended on received result from ssh channel
read 246 returned result
goroutine 246 ended on received result from ssh channel
goroutine 240 started, context expires in 2.977094409s
read 240 is called
goroutine 103 started, context expires in 2.97706947s
read 103 is called
read 240 returned result
goroutine 240 ended on ctx timeout
unable to run command: error reading output from device reader error: context deadline exceeded
```

**Comment by hellt** [comment]
In particular, the interesting stuff happens when we send `ping` command that doesn't have a prompt returned. The following happens:

```bash
< ping command is called, many goroutines start and finish normally until the last two>

goroutine 2 started, context expires in 2.953256809s
read 2 is called
goroutine 218 started, context expires in 2.953201021s
read 218 is called # <- this goroutine 218 entered blocking state, since now prompt is found anymore
read 2 returned result # <- goroutine 2 returned result, but it seems the rrCh is not empty, so it can't write to it
goroutine 2 ended on ctx timeout # <- it ends on timeout instead
unable to run command: error reading output from device reader error: context deadline exceeded

Number of go routines 10
################################################
Sending command: 
Comment:  First enter
Number of go routines 10
Output:
# upon new command we a new pair of goroutines is created
goroutine 147 started, context expires in 2.999854586s
read 147 is called
goroutine 294 started, context expires in 2.999804606s
read 294 is called
read 218 returned result # <- this goroutine was hanging since previous command, but now its able to read from channel as data appears
goroutine 218 ended on ctx timeout # <- but it seems that the channel is destroyed already? since it was part of previous call to readUntilPrompt?
```

**Comment by ogenstad** [comment]
Perhaps also print the error if it's not nil here?

```
func (c *contextReader) read(p []byte, id int) *readResult {
	fmt.Printf("read %v is called\n", id)
	n, err := c.r.Read(p)
	fmt.Printf("read %v returned result\n", id)
	return &readResult{n, err}
}
```

The `read xyz returned result` doesn't have to mean that anything worked. 

As you indicate I'd also suspect that there's an issue with rrCh no longer being active.

A small issue from the example program I posted, the output in the end indicated that there were still 9 goroutines running, in reality that's just a timing issue. If I add a `time.Sleep(500 * time.Millisecond)` on the line after disconnecting from the device it goes back to 1 goroutine when printing. I also tried this when disconnecting before going through the entire ping command where we have 10 goroutines and after closing the connection we're back at 1 goroutine (after waiting half a second at least). However with #11 we have 2 goroutines at that point. If we go with this PR it should be max 1 leaked goroutine per active connection (which won't actually happen that often) I think that's perfectly fine. 

At this point I'm also curious as to what's happening under the hood, but mostly from an academic point of view.

**Comment by hellt** [comment]
so that basically means that in #11 we have a leaking goroutine that doesn't get discarded even when the connection is closed. That is weird...

**Comment by ogenstad** [comment]
Yes, that seems surprising and I don't understand why it would be the case. It could be some other timing issue but I also waited for a few seconds and I think it should have been resolved by then if it wasn't anything permanent.

I just want to run some additional tests and verify that everything looks good if I try to add a larger number of config lines to some test devices ensure that it's behaving as desired in that scenario. Then I think we can merge this.

**Comment by hellt** [comment]
I tried even longer waiting timeouts after closing the device. 35sec. And it was still 2 goroutines reported.
I suppose you want to merge this PR after doing some testing with bigger configs?

**Comment by ogenstad** [comment]
Nice work @hellt, and thank you for your assistance @karimra! Merging this in favor of #11.

**Pull request merged**
